export const MAKE_REQUEST = 'MAKE_REQUEST';
export const GET_IMAGE_DATA = 'GET_IMAGE_DATA'; 
export const IMAGE_DATA_ERROR = 'IMAGE_DATA_ERROR';
export const TOGGLE_FAVORITE_IMAGE = 'TOGGLE_FAVORITE_IMAGE';
export const GET_FAVORITE_IMAGES = 'GET_FAVORITE_IMAGES';
export const DELETE_FAVOURITE_IMAGES = 'DELETE_FAVOURITE_IMAGES';

export const GET_DATE = 'GET_DATE';
export const PREV_DATE = 'PREV_DATE';
export const NEXT_DATE = 'NEXT_DATE';